FROM openjdk:17-jdk-slim

WORKDIR /app

COPY build/libs/CabProject-0.0.1-SNAPSHOT.jar /app/cabproject.jar

# Expose the port that your application will run on
EXPOSE 8086

# Specify the command to run your application
CMD ["java", "-jar", "cabproject.jar"]